### ISSUE TITLE
White inputs on the issue creating form

### ISSUE THREAD

**Issue by vitalyavolyn** [evtn/github-dark#2]
Issue title and description inputs (when focused) are painful to look at!

Also, white background on password confirmation page (link: https://github.com/settings/tokens/new). This was the issue I wanted to report in the first place, but discovered a more critical one

**Comment by evtn** [comment]
the next beta should fix both issues
### ### ### ### ### ### ### 
![last_screenshot](https://user-images.githubusercontent.com/43145587/86045389-b642ea00-ba75-11ea-9fc7-29b38ff49f87.png)

**Comment by evtn** [comment]
Closing as beta fixed it
